import type { Restaurant } from './types';

export const restaurants: Restaurant[] = [
  {
    id: '1',
    name: '钱妈自助快餐',
    area: '汉口',
    category: '其他',
    score: 8.0,
    lunchPrice: '¥19',
    dinnerPrice: '¥28',
    goodReview: '菜品种类多，性价比无敌',
    badReview: '饭点人太多，环境比较吵',
    detailId: 'k5q0hccobtkzlyoo',
  },
  {
    id: '2',
    name: '龍歌自助小火锅(洪山大悦城店)',
    area: '光谷',
    category: '火锅自助',
    score: 8.6,
    lunchPrice: '¥50',
    dinnerPrice: '¥59',
    goodReview: '锅底口味多，不限时不催',
    badReview: '肉类品质一般，补菜有点慢',
    detailId: 'k3bbvxoccwzeparu',
  },
  {
    id: '3',
    name: '39自助火锅',
    area: '武昌',
    category: '海鲜自助',
    score: 7.6,
    lunchPrice: '¥53',
    dinnerPrice: '¥69',
    goodReview: '海鲜种类多，价格很实在',
    badReview: '虾不太新鲜，补货不及时',
    detailId: 'l4iif4glc7csc4r7',
  },
  {
    id: '4',
    name: '骨顶记酱骨烤肉火锅自助餐厅',
    area: '光谷',
    category: '烤涮一体',
    score: 8.6,
    lunchPrice: '¥54',
    dinnerPrice: '¥69',
    goodReview: '酱骨随便啃，肉量很足',
    badReview: '环境油烟大，身上都是味',
    detailId: 'g4ozut9ezwsewjpv',
  },
  {
    id: '5',
    name: '古鲁特烤肉自助餐厅(武汉滨江天街店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥55',
    dinnerPrice: '¥69',
    goodReview: '烤肉品种多，腌得入味',
    badReview: '换纸不勤快，叫了才来',
    detailId: 'l3lzjwmvd3uyu8du',
  },
  {
    id: '6',
    name: '熊喵暴走自助小火锅(新佳丽总店)',
    area: '汉口',
    category: '火锅自助',
    score: 9.2,
    lunchPrice: '¥55',
    dinnerPrice: '¥69',
    goodReview: '小火锅颜值高，菜品种类全',
    badReview: '新佳丽店太挤，排队等很久',
    detailId: 'l9i9x4gx8uzyojdp',
  },
  {
    id: '7',
    name: '疯狂二师兄炭火烧肉自助(江汉路大洋百货店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥56',
    dinnerPrice: '¥69',
    goodReview: '炭火烧肉香，五花肉好吃',
    badReview: '调料区品种少，味道一般',
    detailId: 'ha8orfkiwiwzesg8',
  },
  {
    id: '8',
    name: '炭火东北烧烤自助五点到十一点',
    area: '光谷',
    category: '烤涮一体',
    score: 8.4,
    lunchPrice: '¥56',
    dinnerPrice: '¥69',
    goodReview: '东北味儿正，量大管饱',
    badReview: '晚上才开门，中午吃不到',
    detailId: 'k1a4tfap5qmeuerf',
  },
  {
    id: '9',
    name: '龍歌自助小火锅(武昌万象城店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.6,
    lunchPrice: '¥57',
    dinnerPrice: '¥69',
    goodReview: '环境比大悦城店好，服务热情',
    badReview: '周末人超多，排队一小时起',
    detailId: 'h1jojx08gq0fta2u',
  },
  {
    id: '10',
    name: '炭佬味齐齐哈尔烤肉自助(武汉店)',
    area: '光谷',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥59',
    dinnerPrice: '¥78',
    goodReview: '齐齐哈尔烤肉正宗，牛肉嫩',
    badReview: '位置偏，交通不太方便',
    detailId: 'k7svudrq20yeduwk',
  },
  {
    id: '11',
    name: '火与锅寻·大满足自助小火锅(江汉路店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.8,
    lunchPrice: '¥59',
    dinnerPrice: '¥78',
    goodReview: '牛羊肉新鲜，大满足系列量足',
    badReview: '调料收费，这点有点坑',
    detailId: 'k18t8gethgop9w84',
  },
  {
    id: '12',
    name: '么肆烤肉·中式自助·烤肉大排档(街道口季佳PAI店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥60',
    dinnerPrice: '¥78',
    goodReview: '中式烤肉有烟火气，肉新鲜',
    badReview: '街道口店人多，上菜有点乱',
    detailId: 'l2frsptet9pvgxid',
  },
  {
    id: '13',
    name: '火与锅寻·大满足自助小火锅(街道口店)',
    area: '武昌',
    category: '火锅自助',
    score: 9.4,
    lunchPrice: '¥60',
    dinnerPrice: '¥78',
    goodReview: '蔬菜品种多，补菜速度快',
    badReview: '锅底味道淡，不够浓郁',
    detailId: 'haoccfkljw1n1sfp',
  },
  {
    id: '14',
    name: '姜馆长·韩式无限烤肉(光谷店)',
    area: '光谷',
    category: '烤肉自助',
    score: 9.2,
    lunchPrice: '¥61',
    dinnerPrice: '¥78',
    goodReview: '韩式小菜免费续，烤肉酱好吃',
    badReview: '位子太小，摆不开菜',
    detailId: 'l249ktyylqbsgeyq',
  },
  {
    id: '15',
    name: '火与锅寻·大满足自助小火锅(光谷店)',
    area: '光谷',
    category: '火锅自助',
    score: 8.2,
    lunchPrice: '¥61',
    dinnerPrice: '¥78',
    goodReview: '价格亲民，学生党友好',
    badReview: '光谷店空调不给力，夏天热',
    detailId: 'h2tmzmf8dp4ozzmq',
  },
  {
    id: '16',
    name: '姜胖胖韩式自助烤肉(武汉银泰创意城店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥62',
    dinnerPrice: '¥78',
    goodReview: '韩国老板开的，味道地道',
    badReview: '创意城店周末等位离谱',
    detailId: 'k9rwplkzosnlkdyf',
  },
  {
    id: '17',
    name: '天心屋·锅物料理自助(江汉路中心百货店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.2,
    lunchPrice: '¥62',
    dinnerPrice: '¥79',
    goodReview: '三文鱼新鲜，刺身种类多',
    badReview: '补菜不及时，热门菜靠抢',
    detailId: 'g54rb999yscaodtb',
  },
  {
    id: '18',
    name: '流浪泡泡·破破烂烂的烤肉店(江汉路潮流盒子·X118店)',
    area: '汉口',
    category: '烤肉自助',
    score: 9.6,
    lunchPrice: '¥64',
    dinnerPrice: '¥79',
    goodReview: '装修有个性，肉品质不错',
    badReview: '破破烂烂是真，座位不太舒服',
    detailId: 'l3qhjpsv8lsuvbyc',
  },
  {
    id: '19',
    name: '流浪泡泡·破破烂烂的烤肉店(南湖店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥64',
    dinnerPrice: '¥78',
    goodReview: '南湖店人少些，体验更好',
    badReview: '菜品比江汉路店少一些',
    detailId: 'igescdaerfcugjxk',
  },
  {
    id: '20',
    name: '流浪泡泡·破破烂烂的烤肉店(光谷店)',
    area: '光谷',
    category: '烤肉自助',
    score: 9.2,
    lunchPrice: '¥64',
    dinnerPrice: '¥79',
    goodReview: '服务员响应快，换纸及时',
    badReview: '光谷店排队比南湖店久',
    detailId: 'haf4ahmzcustx40h',
  },
  {
    id: '21',
    name: '姜馆长·韩式无限烤肉(江汉路店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥65',
    dinnerPrice: '¥79',
    goodReview: '牛肋条好吃，蘸料种类多',
    badReview: '江汉路店太小，空气不流通',
    detailId: 'l35lu6gdcawwcqb5',
  },
  {
    id: '22',
    name: '甜甜家烤肉自助(财大店)',
    area: '江夏',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥65',
    dinnerPrice: '¥79',
    goodReview: '烤肉品种多，学生价很值',
    badReview: '财大店周末爆满要等很久',
    detailId: 'b8b19ae1944ed194',
  },
  {
    id: '23',
    name: '众享半岛烤肉.海鲜自助(新洲店)',
    area: '新洲',
    category: '海鲜自助',
    score: 8.0,
    lunchPrice: '¥68',
    dinnerPrice: '¥88',
    goodReview: '海鲜烤肉都有，性价比高',
    badReview: '新洲位置偏，专门跑一趟不值',
    detailId: 'h6hbe4jjrixnxojc',
  },
  {
    id: '24',
    name: '安小牛鲜活牛肉火锅(归元寺远洋里店)',
    area: '汉阳',
    category: '火锅自助',
    score: 8.8,
    lunchPrice: '¥68',
    dinnerPrice: '¥88',
    goodReview: '现切鲜牛肉，涮着吃很嫩',
    badReview: '锅底太清淡，重口味的会嫌淡',
    detailId: 'h5hnnqvfnzsbizgd',
  },
  {
    id: '25',
    name: '安小牛鲜活牛肉火锅(光谷创新天地店)',
    area: '光谷',
    category: '火锅自助',
    score: 8.8,
    lunchPrice: '¥69',
    dinnerPrice: '¥88',
    goodReview: '牛肉品质好，鲜切看得见',
    badReview: '价格比归元寺店贵些，种类一样',
    detailId: 'g4fq78lut7uooan1',
  },
  {
    id: '26',
    name: '比格比萨自助(光谷世界城店)',
    area: '光谷',
    category: '其他',
    score: 7.8,
    lunchPrice: '¥69',
    dinnerPrice: '¥88',
    goodReview: '披萨好吃，炸鸡也不错',
    badReview: '种类偏少，不太像自助餐厅',
    detailId: 'k4lr55njz8ejpfcz',
  },
  {
    id: '27',
    name: '一个串子的故事·自助烤串(南湖店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥70',
    dinnerPrice: '¥89',
    goodReview: '自己烤串有意思，氛围好',
    badReview: '炭火慢，烤熟要等挺久',
    detailId: 'l4vqrdx1ekaih97h',
  },
  {
    id: '28',
    name: '甜甜家自助烤肉(街道口店)',
    area: '武昌',
    category: '烤肉自助',
    score: 7.8,
    lunchPrice: '¥70',
    dinnerPrice: '¥88',
    goodReview: '肉新鲜，蘸料很韩式',
    badReview: '街道口店附近不好停车',
    detailId: '34640f3dfac13115',
  },
  {
    id: '29',
    name: '京滏山烤肉火锅自助料理(光谷鲁巷广场店)',
    area: '光谷',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥71',
    dinnerPrice: '¥88',
    goodReview: '烤肉火锅都有，选择多',
    badReview: '鲁巷店装修老旧，环境扣分',
    detailId: 'kaq3xhubqbwkcuhh',
  },
  {
    id: '30',
    name: '袁炭长自助烤串工厂·烤肉·烧烤(昙华林店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥71',
    dinnerPrice: '¥88',
    goodReview: '自助烤串串大肉多，实在',
    badReview: '昙华林不好停车，建议地铁',
    detailId: 'l1rucnyutyxsygio',
  },
  {
    id: '31',
    name: '盛卡伦海鲜烤肉火锅自助(光谷店)',
    area: '光谷',
    category: '烤涮一体',
    score: 8.6,
    lunchPrice: '¥71',
    dinnerPrice: '¥89',
    goodReview: '海鲜种类多，虾蟹都有',
    badReview: '光谷店人杂，取餐区有点挤',
    detailId: 'k5bipuzz8buktgb0',
  },
  {
    id: '32',
    name: '贰柒柒美蛙鱼自助火锅',
    area: '汉口',
    category: '海鲜自助',
    score: 8.2,
    lunchPrice: '¥71',
    dinnerPrice: '¥88',
    goodReview: '美蛙鱼够味，牛蛙自由',
    badReview: '排队太久，饭点基本要等一小时',
    detailId: 'k8bhcpdtz1nzfnfc',
  },
  {
    id: '33',
    name: '山椒爷爷鲜切牛肉自助老火锅(武昌泛悦Ka街店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.0,
    lunchPrice: '¥71',
    dinnerPrice: '¥88',
    goodReview: '鲜切牛肉好吃，品质稳定',
    badReview: '泛悦汇停车收费贵',
    detailId: 'h6ouul8ln7s5hxfq',
  },
  {
    id: '34',
    name: '盛辛巴·东北炭火烤肉(光谷步行街店)',
    area: '光谷',
    category: '烤肉自助',
    score: 9.2,
    lunchPrice: '¥71',
    dinnerPrice: '¥88',
    goodReview: '东北烤肉量大管饱，肉好',
    badReview: '光谷步行街不好找，容易迷路',
    detailId: 'h379bikzf8dnivlz',
  },
  {
    id: '35',
    name: '尹珍珠·韩式无限烤肉(江汉路店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.4,
    lunchPrice: '¥72',
    dinnerPrice: '¥88',
    goodReview: '韩式小菜多，价格还行',
    badReview: '烤肉偏干，火候不好掌握',
    detailId: 'k623tfz5jp8kqo3y',
  },
  {
    id: '36',
    name: '楚江城自助料理(白沙洲龙湖天街店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.2,
    lunchPrice: '¥72',
    dinnerPrice: '¥88',
    goodReview: '菜品种类还算全，价格适中',
    badReview: '口味平平无奇，没什么记忆点',
    detailId: 'l8mpsiv4qkya43kl',
  },
  {
    id: '37',
    name: '盛辛巴·东北炭火烤肉(南京路总店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥72',
    dinnerPrice: '¥89',
    goodReview: '南京路总店味道最正宗',
    badReview: '排队凶，店面小坐得不舒服',
    detailId: 'h4erlnd72xz4zu3x',
  },
  {
    id: '38',
    name: '布多斯海鲜烤肉自助料理(保利广场店)',
    area: '光谷',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥73',
    dinnerPrice: '¥89',
    goodReview: '海鲜新鲜，三文鱼畅吃',
    badReview: '热门菜容易被拿完，补得慢',
    detailId: 'k6zkcrcv0masvide',
  },
  {
    id: '39',
    name: '烤货熊旋转自助烤肉(江宸天街店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥74',
    dinnerPrice: '¥89',
    goodReview: '旋转自助有意思，孩子喜欢',
    badReview: '菜品转得快，容易错过想吃的',
    detailId: 'l6kblcxbwdc5fasx',
  },
  {
    id: '40',
    name: '豪德亨牛排自助餐厅(武汉经开万达店)',
    area: '汉阳',
    category: '其他',
    score: 8.8,
    lunchPrice: '¥77',
    dinnerPrice: '¥99',
    goodReview: '牛排现煎，肉质还可以',
    badReview: '经开万达这家种类偏少',
    detailId: 'h34fjnjbbbgbruqe',
  },
  {
    id: '41',
    name: '金滏山·烤肉海鲜火锅自助(武汉盘龙城万达店)',
    area: '黄陂',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥78',
    dinnerPrice: '¥98',
    goodReview: '海鲜烤肉品类丰富，吃得过瘾',
    badReview: '盘龙城太远了，交通不便',
    detailId: 'h9dosvzbvxg8hhip',
  },
  {
    id: '42',
    name: '宫略·安格斯鲜牛·自助火锅(光谷步行街店)',
    area: '光谷',
    category: '火锅自助',
    score: 8.0,
    lunchPrice: '¥78',
    dinnerPrice: '¥98',
    goodReview: '安格斯牛肉品质好，汤底浓郁',
    badReview: '价格偏贵，午市才划算',
    detailId: 'l7hapgffk0oafie2',
  },
  {
    id: '43',
    name: '御江盛·烤肉海鲜火锅自助(江汉路M+商场店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥78',
    dinnerPrice: '¥98',
    goodReview: '海鲜烤肉火锅一锅端',
    badReview: '品种虽多但每个都不精',
    detailId: 'l93bs6hcbbh20g5t',
  },
  {
    id: '44',
    name: '醉新火自助烤肉场(南湖佰港城店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥78',
    dinnerPrice: '¥98',
    goodReview: '肉品新鲜，环境装修不错',
    badReview: '南湖店人多嘈杂，聊天靠吼',
    detailId: 'k22wub3sox9pr5sc',
  },
  {
    id: '45',
    name: '红考拉农场旋转自助烤肉(武汉摩尔城店)',
    area: '汉阳',
    category: '烤肉自助',
    score: 8.4,
    lunchPrice: '¥78',
    dinnerPrice: '¥98',
    goodReview: '旋转烤肉形式新颖，好拍照',
    badReview: '摩尔城店菜品不算多',
    detailId: 'g6zlwaigpwdru2t1',
  },
  {
    id: '46',
    name: '牛十三潮汕牛肉火锅(华生广场丰美店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.2,
    lunchPrice: '¥78',
    dinnerPrice: '¥98',
    goodReview: '鲜牛肉现切，涮几秒就能吃',
    badReview: '华生广场附近停车太难了',
    detailId: 'h2wainbznieqda2m',
  },
  {
    id: '47',
    name: '炙の町日式烧肉放题(世界城光谷步行街店)',
    area: '光谷',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥79',
    dinnerPrice: '¥99',
    goodReview: '日式烤肉品质在线，摆盘精致',
    badReview: '光谷步行街店排队太久',
    detailId: 'g7gbrwokyxy10osd',
  },
  {
    id: '48',
    name: '醉新火自助烤肉场(万科未来中心)',
    area: '汉阳',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥79',
    dinnerPrice: '¥99',
    goodReview: '新装修环境好，干净整洁',
    badReview: '周末人多取餐要排队',
    detailId: 'h5jyicox15naiqqw',
  },
  {
    id: '49',
    name: '烤货熊旋转自助烤肉(群光广场店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥80',
    dinnerPrice: '¥99',
    goodReview: '群光广场位置方便，逛完就吃',
    badReview: '旋转台人多了取餐有点乱',
    detailId: 'h6pnvedk5osvatoa',
  },
  {
    id: '50',
    name: '春熹·老北京鲜切涮肉自助(白沙天街店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥80',
    dinnerPrice: '¥99',
    goodReview: '老北京铜锅涮肉，味道正',
    badReview: '价格在小品类里偏高',
    detailId: 'k7atcqrwqx5spfn4',
  },
  {
    id: '51',
    name: '小美与大壮·东北烤肉(M758店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.2,
    lunchPrice: '¥80',
    dinnerPrice: '¥99',
    goodReview: '东北烤肉量大，肉质超预期',
    badReview: 'M758店太小，座位很挤',
    detailId: 'k8bu17szewgoadjp',
  },
  {
    id: '52',
    name: '红考拉农场旋转自助烤肉(武汉白沙龙湖店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.4,
    lunchPrice: '¥80',
    dinnerPrice: '¥99',
    goodReview: '白沙洲新店环境比老店好',
    badReview: '菜品种类和摩尔城一样偏少',
    detailId: 'g1rmivmexeh66wzj',
  },
  {
    id: '53',
    name: '楚江城自助料理(经开万达店)',
    area: '汉阳',
    category: '海鲜自助',
    score: 9.2,
    lunchPrice: '¥81',
    dinnerPrice: '¥99',
    goodReview: '经开万达店环境好，海鲜新鲜',
    badReview: '周末人太多，取餐像打仗',
    detailId: 'l7lrxbq24dncu3e3',
  },
  {
    id: '54',
    name: '布多斯·海鲜烤肉自助料理(新佳丽店)',
    area: '汉口',
    category: '海鲜自助',
    score: 9.2,
    lunchPrice: '¥81',
    dinnerPrice: '¥99',
    goodReview: '新佳丽位置方便，地铁直达',
    badReview: '人流量大，取餐区总排队',
    detailId: 'k5wfpbouab7eewjx',
  },
  {
    id: '55',
    name: '楚江城自助料理(方圆荟奥特莱斯店)',
    area: '汉阳',
    category: '海鲜自助',
    score: 8.4,
    lunchPrice: '¥81',
    dinnerPrice: '¥99',
    goodReview: '方圆荟新店人少，体验不错',
    badReview: '位置偏，周边没什么逛的',
    detailId: 'k2pkl6irmec7dw4i',
  },
  {
    id: '56',
    name: '燕舍·三文鱼特色料理(江汉路店)',
    area: '汉口',
    category: '其他',
    score: 7.6,
    lunchPrice: '¥81',
    dinnerPrice: '¥98',
    goodReview: '三文鱼厚切，品质看得见',
    badReview: '单价偏高，吃回本有点难',
    detailId: 'g9p603f1wdo2p3cd',
  },
  {
    id: '57',
    name: '布多斯·海鲜烤肉自助料理(经开永旺店)',
    area: '汉阳',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥83',
    dinnerPrice: '¥99',
    goodReview: '永旺店停车免费，家庭聚餐方便',
    badReview: '人多取餐乱，补菜跟不上',
    detailId: 'k54yjzysydqtrgqo',
  },
  {
    id: '58',
    name: '佰友成鲜毛肚鲜牛肉自助火锅(新荣天街店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.2,
    lunchPrice: '¥85',
    dinnerPrice: '¥99',
    goodReview: '鲜毛肚不限量，七上八下绝了',
    badReview: '新店开业人多，服务跟不上',
    detailId: 'iigg6ky6opeodxjj',
  },
  {
    id: '59',
    name: '仙人寿司·炙烤料理(汉阳万科店)',
    area: '汉阳',
    category: '其他',
    score: 8.0,
    lunchPrice: '¥86',
    dinnerPrice: '¥109',
    goodReview: '炙烤寿司好吃，菜品精致',
    badReview: '汉阳万科店不算好找',
    detailId: 'k2tzigpmhm2v29hf',
  },
  {
    id: '60',
    name: '潮牛壹号鲜牛肉火锅(银泰创意城店)',
    area: '武昌',
    category: '火锅自助',
    score: 9.4,
    lunchPrice: '¥87',
    dinnerPrice: '¥109',
    goodReview: '现切鲜牛肉，锅底味道超赞',
    badReview: '银泰店周末排队两小时起',
    detailId: 'h95y4pksxc3l0ngy',
  },
  {
    id: '61',
    name: '潮牛壹号鲜牛肉火锅(江夏永旺店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.0,
    lunchPrice: '¥87',
    dinnerPrice: '¥109',
    goodReview: '江夏永旺新店宽敞，不用等',
    badReview: '牛肉品种比其他分店少',
    detailId: 'fwe6lsslb3kgfp13',
  },
  {
    id: '62',
    name: '潮牛壹号鲜牛肉火锅(金银潭永旺店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.4,
    lunchPrice: '¥87',
    dinnerPrice: '¥109',
    goodReview: '金银潭店服务好，主动加汤',
    badReview: '永旺周末人爆炸，早点去',
    detailId: 'l8iu6rfzvyj1ojs7',
  },
  {
    id: '63',
    name: '点都德(武商梦时代店)',
    area: '武昌',
    category: '其他',
    score: 9.4,
    lunchPrice: '¥87',
    dinnerPrice: '¥108',
    goodReview: '茶点精致，虾饺肠粉都好吃',
    badReview: '不是传统自助，加菜要等',
    detailId: 'g6wj7uugxtswnrmz',
  },
  {
    id: '64',
    name: '潮牛壹号鲜牛肉火锅(白沙龙湖天街店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.6,
    lunchPrice: '¥88',
    dinnerPrice: '¥109',
    goodReview: '牛肉新鲜看得见，汤底香浓',
    badReview: '白沙洲店位置偏，公交不便',
    detailId: 'l6wumvqnv99uogz1',
  },
  {
    id: '65',
    name: '潮牛壹号鲜牛肉火锅(群星城店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.2,
    lunchPrice: '¥88',
    dinnerPrice: '¥108',
    goodReview: '群星城店环境好，约会首选',
    badReview: '服务员忙不过来，加菜靠喊',
    detailId: 'g9s2ishnp23i6q6f',
  },
  {
    id: '66',
    name: '富匠·安格斯鲜牛肉·烧肉放题自助(范湖万达店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.2,
    lunchPrice: '¥88',
    dinnerPrice: '¥108',
    goodReview: '安格斯牛肉品质高，炭火香',
    badReview: '范湖万达停车费小贵',
    detailId: 'l7tmbib6vpwo1jac',
  },
  {
    id: '67',
    name: '滏晓烤肉海鲜火锅自助(光谷星悦广场店)',
    area: '光谷',
    category: '海鲜自助',
    score: 9.4,
    lunchPrice: '¥89',
    dinnerPrice: '¥118',
    goodReview: '海鲜品类全，虾蟹贝都有',
    badReview: '光谷星悦广场店服务态度一般',
    detailId: 'k5cwttjltzykuj8o',
  },
  {
    id: '68',
    name: '滏晓烤肉海鲜火锅自助(洪山万科广场店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥89',
    dinnerPrice: '¥109',
    goodReview: '洪山万科环境好，适合家庭',
    badReview: '价格上去了品质没跟上',
    detailId: 'g9kpfp7ombszsjyw',
  },
  {
    id: '69',
    name: '烤肉名家•朝鲜族自助烤肉(雄楚一号店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.0,
    lunchPrice: '¥89',
    dinnerPrice: '¥109',
    goodReview: '朝鲜族烤肉地道，蘸料特别',
    badReview: '雄楚大道堵车，出门就堵',
    detailId: 'hayo0ecyqxx0iwyc',
  },
  {
    id: '70',
    name: '牧牛道·鲜牛肉自助火锅(光谷广场店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.6,
    lunchPrice: '¥89',
    dinnerPrice: '¥109',
    goodReview: '鲜牛肉现切不限量，爽',
    badReview: '光谷广场附近不好停车',
    detailId: 'ikqwds67b97rumut',
  },
  {
    id: '71',
    name: '汉江山料理级自助烤肉(武汉大悦城店)',
    area: '光谷',
    category: '海鲜自助',
    score: 8.4,
    lunchPrice: '¥90',
    dinnerPrice: '¥118',
    goodReview: '大悦城环境不错，品类多',
    badReview: '味道平平，不值这个价',
    detailId: 'ebe6g7w2swrdiijo',
  },
  {
    id: '72',
    name: '佰友成鲜毛肚鲜牛肉自助火锅(茶码头店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥90',
    dinnerPrice: '¥118',
    goodReview: '毛肚新鲜，七上八下脆爽',
    badReview: '茶码头店位置不起眼不太好找',
    detailId: 'g8m4xn1efzbks7mv',
  },
  {
    id: '73',
    name: '潮牛壹号鲜牛肉火锅(滨江天街甄选店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.4,
    lunchPrice: '¥90',
    dinnerPrice: '¥109',
    goodReview: '滨江天街新店环境加分',
    badReview: '锅底选择没有银泰店多',
    detailId: 'l6zoxygrswunce0h',
  },
  {
    id: '74',
    name: '宫略·安格斯鲜牛自助火锅(江汉路新佳丽店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.4,
    lunchPrice: '¥90',
    dinnerPrice: '¥109',
    goodReview: '江汉路位置方便，逛完吃',
    badReview: '新佳丽人多到爆，空调不够',
    detailId: 'k7mfp9dsrusde3sc',
  },
  {
    id: '75',
    name: '欢乐牧场主题自助料理(金桥永旺店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.6,
    lunchPrice: '¥91',
    dinnerPrice: '¥118',
    goodReview: '金桥永旺环境好，带孩子方便',
    badReview: '口味普通没亮点，价格偏高',
    detailId: 'g995u4lm7ndbk4qc',
  },
  {
    id: '76',
    name: 'Fire Door·火门美式烤肉(武汉天地店)',
    area: '汉口',
    category: '烤肉自助',
    score: 7.4,
    lunchPrice: '¥92',
    dinnerPrice: '¥109',
    goodReview: '美式烤肉风格独特，肉香浓郁',
    badReview: '武汉天地周边停车又贵又难',
    detailId: 'g9gihkyoqcilzxjw',
  },
  {
    id: '77',
    name: '潮牛壹号鲜牛肉火锅(世界城广场店)',
    area: '光谷',
    category: '火锅自助',
    score: 8.6,
    lunchPrice: '¥92',
    dinnerPrice: '¥118',
    goodReview: '世界城店牛肉品质最好',
    badReview: '价格偏高，午市才划算一些',
    detailId: 'h3vgpyzbrhnn9551',
  },
  {
    id: '78',
    name: '汉江山料理级自助烤肉(江夏永旺店)',
    area: '武昌',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥93',
    dinnerPrice: '¥118',
    goodReview: '江夏永旺人少，不用排队',
    badReview: '菜品和别的汉江山差不多，没惊喜',
    detailId: 'k81sl7apq95aa1vy',
  },
  {
    id: '79',
    name: '自在烧肉·放题自助专门店(江汉路店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.4,
    lunchPrice: '¥93',
    dinnerPrice: '¥118',
    goodReview: '日式烧肉品质好，性价比高',
    badReview: '放题有时间限制，吃得不自在',
    detailId: 'g1dlxgebeyh2yvc0',
  },
  {
    id: '80',
    name: '宫略·安格斯鲜牛自助火锅(街道口店)',
    area: '武昌',
    category: '海鲜自助',
    score: 8.2,
    lunchPrice: '¥94',
    dinnerPrice: '¥109',
    goodReview: '街道口学生多，氛围热闹',
    badReview: '没什么特色，就是普通的自助',
    detailId: 'ha9fbvqrt7fi9kcm',
  },
  {
    id: '81',
    name: '潮牛壹号鲜牛肉火锅(光谷保利广场店)',
    area: '光谷',
    category: '火锅自助',
    score: 8.0,
    lunchPrice: '¥94',
    dinnerPrice: '¥109',
    goodReview: '保利广场店人少不用排队',
    badReview: '光谷保利附近修路，路况差',
    detailId: 'g6anuc763bbmuekx',
  },
  {
    id: '82',
    name: '名家大作·朝鲜族自助烤肉(万象汇店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.2,
    lunchPrice: '¥94',
    dinnerPrice: '¥118',
    goodReview: '朝鲜族烤肉量大管饱',
    badReview: '万象汇停车收费高',
    detailId: 'l7yyez18npdowckx',
  },
  {
    id: '83',
    name: '潮很鲜·海鲜榴莲·刺身日料·鲜牛肉火锅自助(光谷世...',
    area: '光谷',
    category: '海鲜自助',
    score: 9.4,
    lunchPrice: '¥95',
    dinnerPrice: '¥118',
    goodReview: '海鲜榴莲不限量，值回票价',
    badReview: '名字太长连店名都记不住',
    detailId: 'h3ukxfxhrnqnqun5',
  },
  {
    id: '84',
    name: '安记潮牛鲜牛肉火锅(光谷泛悦城店)',
    area: '光谷',
    category: '火锅自助',
    score: 9.0,
    lunchPrice: '¥95',
    dinnerPrice: '¥118',
    goodReview: '潮汕牛肉新鲜，现切现吃',
    badReview: '泛悦城附近不太好停车',
    detailId: 'l24d9mh4meuiqo5a',
  },
  {
    id: '85',
    name: '潮很鲜鲜切牛肉工坊自助火锅(汉街万达店)',
    area: '武昌',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥95',
    dinnerPrice: '¥118',
    goodReview: '汉街万达环境高档，有面子',
    badReview: '价格不便宜，海鲜品种有限',
    detailId: 'k2ec113z6mu6ks9s',
  },
  {
    id: '86',
    name: '潮很鲜牛肉工坊自助火锅(中商广场店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥96',
    dinnerPrice: '¥118',
    goodReview: '中商广场地理位置好',
    badReview: '人多的时候加菜跟不上',
    detailId: 'hay4shsbudkfq4uy',
  },
  {
    id: '87',
    name: '炽城·烤肉名家(鸿达中央广场店)',
    area: '东西湖',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥97',
    dinnerPrice: '¥128',
    goodReview: '烤肉品质好，口碑炸裂',
    badReview: '东西湖太偏了，专程跑一趟累',
    detailId: 'g1tsuw3bexhmghwu',
  },
  {
    id: '88',
    name: '安记潮牛鲜牛肉火锅(国金天地店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.4,
    lunchPrice: '¥98',
    dinnerPrice: '¥118',
    goodReview: '国金天地环境好，肉品质稳定',
    badReview: '价格偏高，虾滑限量',
    detailId: 'l9whsgansxf5pfts',
  },
  {
    id: '89',
    name: '潮牛壹号鲜牛肉火锅(江宸天街店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.4,
    lunchPrice: '¥98',
    dinnerPrice: '¥128',
    goodReview: '江宸天街店交通方便',
    badReview: '周末人多服务跟不上',
    detailId: 'h9ouxevid1gwb1j2',
  },
  {
    id: '90',
    name: '潮很鲜鲜切牛肉工坊自助火锅(汉阳万科店)',
    area: '汉阳',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥100',
    dinnerPrice: '¥119',
    goodReview: '汉阳万科新店环境干净',
    badReview: '¥100起步，小贵',
    detailId: 'l4tahcafthax5ibq',
  },
  {
    id: '91',
    name: '喜庭海鲜火锅(武汉万象城店)',
    area: '汉口',
    category: '海鲜自助',
    score: 9.4,
    lunchPrice: '¥100',
    dinnerPrice: '¥128',
    goodReview: '万象城环境高级，海鲜新鲜',
    badReview: '价格不菲，吃回本需要功力',
    detailId: 'h5dahxnoohkq0pg1',
  },
  {
    id: '92',
    name: '喜庭海鲜火锅(武昌万象城店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥100',
    dinnerPrice: '¥128',
    goodReview: '武昌万象城新店，环境大气',
    badReview: '服务和口味配不上这个价格',
    detailId: 'l1kqemffj1gfoqsi',
  },
  {
    id: '93',
    name: '谭三娘鲜切牛肉自助火锅(联投广场店)',
    area: '江夏',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥101',
    dinnerPrice: '¥128',
    goodReview: '鲜切牛肉品质好回头客多',
    badReview: '联投广场附近没啥逛的',
    detailId: 'k65bed1gjibtxdcb',
  },
  {
    id: '94',
    name: '潮很鲜·海鲜榴莲·刺身日料·鲜牛肉火锅(硚口荟聚黑...',
    area: '东西湖',
    category: '火锅自助',
    score: 8.6,
    lunchPrice: '¥105',
    dinnerPrice: '¥128',
    goodReview: '荟聚店海鲜品种多还有榴莲',
    badReview: '位置偏，从市区过去有点远',
    detailId: 'jcnc5tegmaci2jyl',
  },
  {
    id: '95',
    name: '海鲜时间自助餐厅(武汉店)',
    area: '汉口',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥105',
    dinnerPrice: '¥129',
    goodReview: '海鲜种类全，虾蟹不限量',
    badReview: '口味一般，海鲜不太新鲜',
    detailId: 'g73z6roof7puu6ft',
  },
  {
    id: '96',
    name: '八斗寿喜烧·和牛海鲜榴莲放题自助(王家湾摩尔城店)',
    area: '汉阳',
    category: '火锅自助',
    score: 8.2,
    lunchPrice: '¥108',
    dinnerPrice: '¥129',
    goodReview: '和牛海鲜榴莲都能吃到',
    badReview: '摩尔城店人多座挤座',
    detailId: 'g90zy0yzklu9dzjc',
  },
  {
    id: '97',
    name: '牛匠和牛寿喜锅(街道口季佳PAI店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.2,
    lunchPrice: '¥109',
    dinnerPrice: '¥138',
    goodReview: '和牛品质不错，寿喜锅底甜香',
    badReview: '街道口店周末排队人山人海',
    detailId: 'h4ktaai3bkmfj4jc',
  },
  {
    id: '98',
    name: '玫瑰烤房·美式熏肉自助(万松园店)',
    area: '汉口',
    category: '烤肉自助',
    score: 7.6,
    lunchPrice: '¥110',
    dinnerPrice: '¥138',
    goodReview: '美式熏肉有特色，分量足',
    badReview: '万松园路窄不好停车',
    detailId: 'g3i13jdovklwqb6b',
  },
  {
    id: '99',
    name: '八斗寿喜烧·和牛海鲜榴莲放题自助(江宸天街店)',
    area: '汉口',
    category: '火锅自助',
    score: 7.6,
    lunchPrice: '¥115',
    dinnerPrice: '¥139',
    goodReview: '江宸天街店环境好，逛街顺路吃',
    badReview: '榴莲品质不稳定，时好时坏',
    detailId: 'k1xgaa1ncpft9tus',
  },
  {
    id: '100',
    name: '八斗寿喜烧·和牛海鲜榴莲放题自助(新佳丽店)',
    area: '汉口',
    category: '火锅自助',
    score: 8.0,
    lunchPrice: '¥117',
    dinnerPrice: '¥139',
    goodReview: '新佳丽店地理位置方便',
    badReview: '¥117起步性价比不太行',
    detailId: 'g1wdoa3m7obof8kw',
  },
  {
    id: '101',
    name: '西月山居·炭烤活鳗烧肉自助(汉街万达广场店)',
    area: '武昌',
    category: '烤肉自助',
    score: 9.2,
    lunchPrice: '¥119',
    dinnerPrice: '¥148',
    goodReview: '活鳗现烤，品质看得见',
    badReview: '汉街万达价格贵，性价比一般',
    detailId: 'eajnshznszrctpuq',
  },
  {
    id: '102',
    name: '布罗城堡·海鲜·牛排·烤肉自助餐厅(凯德西城店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.4,
    lunchPrice: '¥120',
    dinnerPrice: '¥139',
    goodReview: '海鲜牛排烤肉都有，品种多',
    badReview: '品种多但都不精，口味平平',
    detailId: 'g27n1wxbpi6k7d1j',
  },
  {
    id: '103',
    name: '赤牧日式烧肉自助(江汉路新佳丽店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥121',
    dinnerPrice: '¥149',
    goodReview: '日式烧肉品质一流，回头客多',
    badReview: '新佳丽店人多排队太久',
    detailId: 'g8de0b8hynborsjw',
  },
  {
    id: '104',
    name: '赤牧日式烧肉自助(光谷星悦广场店)',
    area: '光谷',
    category: '烤肉自助',
    score: 8.4,
    lunchPrice: '¥122',
    dinnerPrice: '¥149',
    goodReview: '光谷店人少，体验比新佳丽好',
    badReview: '停车不方便，建议地铁',
    detailId: 'h18fcdsqrqm0jpyn',
  },
  {
    id: '105',
    name: '赤牧日式烧肉自助(世界城广场店)',
    area: '光谷',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥123',
    dinnerPrice: '¥149',
    goodReview: '世界城店环境好，约会合适',
    badReview: '价格偏高，服务匹配不上',
    detailId: 'h9xvy03gd92t5ode',
  },
  {
    id: '106',
    name: '霜炙鲜活海鲜烧肉酒场自助餐厅(江夏中百广场店)',
    area: '江夏',
    category: '海鲜自助',
    score: 8.4,
    lunchPrice: '¥125',
    dinnerPrice: '¥159',
    goodReview: '海鲜和烧肉品质都在线',
    badReview: '江夏中百周末人多要等',
    detailId: 'g6p9ph6u1jynmg6w',
  },
  {
    id: '107',
    name: '赤牧日式烧肉自助(武昌万象城店)',
    area: '武昌',
    category: '烤肉自助',
    score: 9.0,
    lunchPrice: '¥127',
    dinnerPrice: '¥149',
    goodReview: '万象城店环境最好，空间大',
    badReview: '¥127起步，午市才划算',
    detailId: 'eocxo5yzsm5xxgo1',
  },
  {
    id: '108',
    name: '赤牧日式烧肉自助(楚河汉街店)',
    area: '武昌',
    category: '烤肉自助',
    score: 9.0,
    lunchPrice: '¥127',
    dinnerPrice: '¥159',
    goodReview: '楚河汉街地段好，逛完就吃',
    badReview: '排队太久，取餐区小',
    detailId: 'exflm0ihqdcdgyjr',
  },
  {
    id: '109',
    name: '1718海鲜姿造·火锅(沙湖桃源国际店)',
    area: '武昌',
    category: '火锅自助',
    score: 9.0,
    lunchPrice: '¥129',
    dinnerPrice: '¥159',
    goodReview: '海鲜品质高，三文鱼自由',
    badReview: '价格偏高，偶尔吃一次还行',
    detailId: 'g53xmazoutp9btw9',
  },
  {
    id: '110',
    name: '赤牧日式烧肉自助(金桥永旺店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥129',
    dinnerPrice: '¥158',
    goodReview: '金桥永旺店品质最稳定',
    badReview: '永旺周末停车像打仗',
    detailId: 'l7rgif0vbtcnht8s',
  },
  {
    id: '111',
    name: '赤牧日式烧肉自助(摩尔城店)',
    area: '汉阳',
    category: '烤肉自助',
    score: 8.0,
    lunchPrice: '¥130',
    dinnerPrice: '¥159',
    goodReview: '摩尔城店服务好，肉质上乘',
    badReview: '¥130起步价位偏高',
    detailId: 'k9zplcrrjxi4g2pf',
  },
  {
    id: '112',
    name: '赤牧日式烧肉自助(武商MALL店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥139',
    dinnerPrice: '¥169',
    goodReview: '武商MALL位置黄金，档次高',
    badReview: '价格偏高，热门肉品限量',
    detailId: 'fumnyqrgvmmqc6hn',
  },
  {
    id: '113',
    name: '海宫造·海鲜自助料理铁板烧',
    area: '武昌',
    category: '海鲜自助',
    score: 7.8,
    lunchPrice: '¥147',
    dinnerPrice: '¥188',
    goodReview: '海鲜种类丰富，刺身自由',
    badReview: '¥147偏贵，性价比不如新極膳',
    detailId: 'h7dzaapqdl1jx5mc',
  },
  {
    id: '114',
    name: '亚马逊海鲜自助·蒸汽海鲜(梦时代店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.2,
    lunchPrice: '¥149',
    dinnerPrice: '¥178',
    goodReview: '蒸汽海鲜新鲜，原汁原味',
    badReview: '梦时代店周末人多到爆炸',
    detailId: 'k8jrn5e22yp0htrp',
  },
  {
    id: '115',
    name: '亚马逊海鲜自助·蒸汽海鲜(国广店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥154',
    dinnerPrice: '¥188',
    goodReview: '国广店环境好，海鲜品质高',
    badReview: '¥154起步不便宜',
    detailId: 'g3gzx4xx4gffweyp',
  },
  {
    id: '116',
    name: '亚马逊海鲜自助·蒸汽海鲜(销品茂店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥155',
    dinnerPrice: '¥189',
    goodReview: '销品茂店人相对少一点',
    badReview: '价格偏高，服务水平不稳定',
    detailId: 'h2p2kxdpk0m1cvqk',
  },
  {
    id: '117',
    name: '武汉厨房自助餐厅·武汉卓尔万豪酒店',
    area: '汉口',
    category: '海鲜自助',
    score: 8.0,
    lunchPrice: '¥155',
    dinnerPrice: '¥188',
    goodReview: '万豪酒店品质，环境服务一流',
    badReview: '价格偏高，种类不如新極膳',
    detailId: 'h3k0r0xbp0ldwzad',
  },
  {
    id: '118',
    name: '金马门国际美食百汇(珞喻路店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.2,
    lunchPrice: '¥159',
    dinnerPrice: '¥198',
    goodReview: '珞喻路老店，品类齐全',
    badReview: '周末人太多，像菜市场',
    detailId: 'lawrcshusoqbweyk',
  },
  {
    id: '119',
    name: '驭山海·海鲜·火锅烤肉自助(武汉新天地店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥160',
    dinnerPrice: '¥189',
    goodReview: '新天地地段高大上',
    badReview: '海鲜品质不稳定，看运气',
    detailId: 'k8a37n30lektgub4',
  },
  {
    id: '120',
    name: '喜来登大酒店-盛宴标帜自助餐厅',
    area: '汉口',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥161',
    dinnerPrice: '¥189',
    goodReview: '喜来登出品，品质有保障',
    badReview: '价格偏贵，菜品偏少',
    detailId: 'k2gewzbbl9cvmwek',
  },
  {
    id: '121',
    name: '锅藏寿喜烧·和牛自助放题(银泰创意城店)',
    area: '武昌',
    category: '火锅自助',
    score: 8.4,
    lunchPrice: '¥165',
    dinnerPrice: '¥198',
    goodReview: '和牛自助品质高，锅底浓郁',
    badReview: '¥165偏贵，吃多会腻',
    detailId: 'k6skfnii9qni9pju',
  },
  {
    id: '122',
    name: '环璟·蒸汽海鲜·刺身火锅(荟聚广场店)',
    area: '东西湖',
    category: '海鲜自助',
    score: 8.4,
    lunchPrice: '¥167',
    dinnerPrice: '¥199',
    goodReview: '荟聚店环境好，海鲜蒸汽鲜',
    badReview: '价格偏高，人不多但菜也少',
    detailId: 'k4ktmnlyczojxmbn',
  },
  {
    id: '123',
    name: '驭山海鲜炙山海汇自助(武昌滨江天街店)',
    area: '武昌',
    category: '海鲜自助',
    score: 7.8,
    lunchPrice: '¥167',
    dinnerPrice: '¥208',
    goodReview: '滨江天街店位置好',
    badReview: '不值这个价，品质配不上价格',
    detailId: 'l95z6ng2zqpc63z8',
  },
  {
    id: '124',
    name: '花见小鹿·烧肉海鲜放题自助专门店(苗栗路店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥170',
    dinnerPrice: '¥208',
    goodReview: '烧肉海鲜品质双高，值回价',
    badReview: '苗栗路附近不太好停车',
    detailId: 'h2gblucamxwdgfdk',
  },
  {
    id: '125',
    name: '环璟·蒸汽海鲜·刺身火锅(江宸天街店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥172',
    dinnerPrice: '¥218',
    goodReview: '江宸天街店海鲜品种丰富',
    badReview: '价格涨了不少，没性价比了',
    detailId: 'g9anrkbpvavedgzd',
  },
  {
    id: '126',
    name: '一緒に寿喜烧(恒隆广场店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥173',
    dinnerPrice: '¥199',
    goodReview: '和牛寿喜烧界的天花板',
    badReview: '恒隆停车贵，人均¥200起步',
    detailId: 'g5jcllgyp0rllady',
  },
  {
    id: '127',
    name: '驭山海.鲜炙山海汇自助餐厅(国金商场店)',
    area: '汉口',
    category: '海鲜自助',
    score: 7.6,
    lunchPrice: '¥173',
    dinnerPrice: '¥218',
    goodReview: '国金商场环境高档',
    badReview: '菜少价高，踩雷了',
    detailId: 'kapcvmhhne2gxifs',
  },
  {
    id: '128',
    name: '板楽烧·铁板烧·海鲜牛排自助(武汉新天地店)',
    area: '汉口',
    category: '烤肉自助',
    score: 7.6,
    lunchPrice: '¥178',
    dinnerPrice: '¥218',
    goodReview: '铁板烧现做现吃，体验好',
    badReview: '¥178偏贵，份量不算大',
    detailId: 'lamlux6np2kzwosd',
  },
  {
    id: '129',
    name: '一緒に寿喜烧(武昌万象城店)',
    area: '武昌',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥187',
    dinnerPrice: '¥219',
    goodReview: '和牛品质顶，服务态度好',
    badReview: '武昌万象城停车贵，交通不便',
    detailId: 'k1qx1atmdgprsgjx',
  },
  {
    id: '130',
    name: '板楽烧·铁板烧·海鲜牛排自助(光谷天地店)',
    area: '光谷',
    category: '烤肉自助',
    score: 8.6,
    lunchPrice: '¥190',
    dinnerPrice: '¥238',
    goodReview: '食材新鲜，铁板烧师傅手艺好',
    badReview: '光谷天地堵车，出门就心烦',
    detailId: 'l1lxn7zpz3qyxh8p',
  },
  {
    id: '131',
    name: '漢咖啡·全服务式自助晚餐(武汉洲际酒店)',
    area: '汉阳',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥190',
    dinnerPrice: '¥238',
    goodReview: '洲际酒店出品，环境无敌',
    badReview: '价格偏高，性价比一般',
    detailId: 'h70o0oeywfhall5y',
  },
  {
    id: '132',
    name: '新極膳·海鲜艺食料理(星悦广场店)',
    area: '光谷',
    category: '海鲜自助',
    score: 8.4,
    lunchPrice: '¥221',
    dinnerPrice: '¥259',
    goodReview: '海鲜品质一流，刺身自由',
    badReview: '星悦广场位置偏了点',
    detailId: 'h3whznjczzqza8f0',
  },
  {
    id: '133',
    name: '新極膳·海鲜艺食料理(新荣天街店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥221',
    dinnerPrice: '¥269',
    goodReview: '新荣天街新店环境超赞',
    badReview: '价格不菲，偶尔犒劳自己',
    detailId: 'g8xsspbb4fvsc0pq',
  },
  {
    id: '134',
    name: '匠和风精致料理(武昌万象城店)',
    area: '武昌',
    category: '烤肉自助',
    score: 8.0,
    lunchPrice: '¥232',
    dinnerPrice: '¥278',
    goodReview: '匠和风精致，摆盘像艺术品',
    badReview: '¥232起步，人均奔着¥300去',
    detailId: 'g8bzj5gcbxipiuxr',
  },
  {
    id: '135',
    name: '新極膳·海鲜艺食料理(佰港城店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.2,
    lunchPrice: '¥237',
    dinnerPrice: '¥288',
    goodReview: '佰港城店海鲜品质稳定',
    badReview: '价格偏高，不是日常消费',
    detailId: 'h34bi8aco2ghbvxf',
  },
  {
    id: '136',
    name: '匠和风精致料理(武汉万象城店)',
    area: '汉口',
    category: '烤肉自助',
    score: 8.8,
    lunchPrice: '¥242',
    dinnerPrice: '¥289',
    goodReview: '匠心出品，每道菜都精致',
    badReview: '¥242太贵，性价比打问号',
    detailId: 'g7n75k8povcikuxw',
  },
  {
    id: '137',
    name: '大渔臻选·棠膳(武昌万象城店)',
    area: '武昌',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥253',
    dinnerPrice: '¥308',
    goodReview: '大渔臻选品质，高端体验',
    badReview: '¥253不便宜，适合特殊日子',
    detailId: 'haxb75apidudtjkm',
  },
  {
    id: '138',
    name: '新極膳·海鲜艺食料理(光谷世界城店)',
    area: '光谷',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥264',
    dinnerPrice: '¥309',
    goodReview: '世界城店品质稳定，服务好',
    badReview: '¥264价格劝退不少人',
    detailId: 'l11zkpkgi8f5dtvp',
  },
  {
    id: '139',
    name: '万达瑞华酒店美食汇自助餐厅(楚河汉街店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.4,
    lunchPrice: '¥265',
    dinnerPrice: '¥319',
    goodReview: '瑞华酒店出品，档次拉满',
    badReview: '价格太高，性价比一般',
    detailId: 'l7gnvpelv2baafva',
  },
  {
    id: '140',
    name: '新極膳·海鲜艺食料理(群光广场店)',
    area: '武昌',
    category: '海鲜自助',
    score: 8.2,
    lunchPrice: '¥266',
    dinnerPrice: '¥328',
    goodReview: '群光广场店环境最优雅',
    badReview: '太贵，且群光停车很贵',
    detailId: 'l7wcg7tesphvjww0',
  },
  {
    id: '141',
    name: '新極膳·海鲜艺食料理(亲橙万象汇店)',
    area: '武昌',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥268',
    dinnerPrice: '¥318',
    goodReview: '亲橙万象汇新店体验极佳',
    badReview: '价格劝退，除非有人请客',
    detailId: 'g5tu0arbcvg6exta',
  },
  {
    id: '142',
    name: '新極膳·海鲜艺食料理(汉街万达店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.4,
    lunchPrice: '¥270',
    dinnerPrice: '¥318',
    goodReview: '汉街万达店位置绝佳',
    badReview: '¥270起步，真的贵',
    detailId: 'g6jwwn1jso1vsecb',
  },
  {
    id: '143',
    name: '新極膳·海鲜艺食料理(摩尔城店)',
    area: '汉阳',
    category: '海鲜自助',
    score: 8.2,
    lunchPrice: '¥272',
    dinnerPrice: '¥318',
    goodReview: '摩尔城店环境安静舒适',
    badReview: '¥272太贵了，吃一次肉疼',
    detailId: 'l46kj2fchwhn1ywf',
  },
  {
    id: '144',
    name: '新極膳·海鲜艺食料理(江宸天街店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥272',
    dinnerPrice: '¥338',
    goodReview: '江宸天街店品质一如既往好',
    badReview: '价格摆在那，不能常去',
    detailId: 'k4384t6cnhrnfls8',
  },
  {
    id: '145',
    name: '大渔臻选·棠膳(汉口万象城店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥275',
    dinnerPrice: '¥338',
    goodReview: '汉口万象城环境高档',
    badReview: '¥275太贵，服务跟不上价格',
    detailId: 'gautzvo3frfyyhv8',
  },
  {
    id: '146',
    name: '新極膳·海鲜艺食料理(北辰光谷里店)',
    area: '光谷',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥279',
    dinnerPrice: '¥338',
    goodReview: '北辰光谷里店人少体验好',
    badReview: '价格太高，光谷学生党劝退',
    detailId: 'l1ktd02ylzq9amu2',
  },
  {
    id: '147',
    name: '新極膳·海鲜艺食料理(循礼门店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥290',
    dinnerPrice: '¥358',
    goodReview: '循礼门店地段好，品质顶',
    badReview: '¥290不亲民，只能特别日子去',
    detailId: 'g36hdu5m8r4tswsr',
  },
  {
    id: '148',
    name: '新極膳·海鲜艺食料理(三阳路店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.2,
    lunchPrice: '¥299',
    dinnerPrice: '¥369',
    goodReview: '三阳路店服务最专业',
    badReview: '¥299太贵，打工人吃不起',
    detailId: 'l8ir9lruwlh5jqmr',
  },
  {
    id: '149',
    name: '新極膳·海鲜艺食料理(沙湖店)',
    area: '武昌',
    category: '海鲜自助',
    score: 9.0,
    lunchPrice: '¥307',
    dinnerPrice: '¥379',
    goodReview: '沙湖店品质第一，评分最高',
    badReview: '¥307天价，只能仰望',
    detailId: 'g1mjbsi7buoh6ws0',
  },
  {
    id: '150',
    name: '花潮料理艺食馆(武汉万象城店)',
    area: '汉口',
    category: '海鲜自助',
    score: 9.4,
    lunchPrice: '¥324',
    dinnerPrice: '¥398',
    goodReview: '花潮出品精致，仪式感满满',
    badReview: '¥324吃一次大半个月工资',
    detailId: 'hatp1w78dwbgkyp6',
  },
  {
    id: '151',
    name: '新極膳·海鲜艺食料理(恒隆黑钻店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.8,
    lunchPrice: '¥410',
    dinnerPrice: '¥498',
    goodReview: '恒隆黑钻店体验天花板',
    badReview: '¥410是真的贵，不忍心看账单',
    detailId: 'l840wlfbuuglyud2',
  },
  {
    id: '152',
    name: '雍容荟活波龙自助餐(武汉恒隆广场黑金店)',
    area: '汉口',
    category: '海鲜自助',
    score: 8.6,
    lunchPrice: '¥516',
    dinnerPrice: '¥639',
    goodReview: '活波龙不限量，豪横体验',
    badReview: '¥516起步，看一眼价格就饱了',
    detailId: 'k8sksxpe0edjht0w',
  },
];

export const areas = ['全部区域', '东西湖', '光谷', '新洲', '武昌', '汉口', '汉阳', '江夏', '黄陂'];
export const categories = ['全部类型', '其他', '海鲜自助', '火锅自助', '烤涮一体', '烤肉自助'];
export const priceRanges = [
  '全部价格',
  '¥100以下',
  '¥100-200',
  '¥200-300',
  '¥300以上',
];
